#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

#execute in gitlab-app: gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token"
#execute in gitlab-runner: https://docs.gitlab.com/runner/register/index.html

if [ -n "$GITLAB_RUNNER_TOKEN" ] ; then
  podman exec -t gitlab-runner gitlab-runner register --url https://$HOST --token "$GITLAB_RUNNER_TOKEN"
fi
